"""empty message

Revision ID: 1dbed4ac1671
Revises: 5e79a513acf0
Create Date: 2022-05-10 02:37:42.908073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbed4ac1671'
down_revision = '5e79a513acf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Characters', sa.Column('image_url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'Characters', ['image_url'])
    op.add_column('Planets', sa.Column('image_url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'Planets', ['image_url'])
    op.add_column('Starships', sa.Column('image_url', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'Starships', ['image_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Starships', type_='unique')
    op.drop_column('Starships', 'image_url')
    op.drop_constraint(None, 'Planets', type_='unique')
    op.drop_column('Planets', 'image_url')
    op.drop_constraint(None, 'Characters', type_='unique')
    op.drop_column('Characters', 'image_url')
    # ### end Alembic commands ###
