"""empty message

Revision ID: 22b204ccf59d
Revises: d539075497ff
Create Date: 2022-05-09 23:46:57.582417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b204ccf59d'
down_revision = 'd539075497ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Starships')
    # ### end Alembic commands ###
