"""empty message

Revision ID: 2c8ad1d68f2f
Revises: 8e61001e64cf
Create Date: 2022-05-09 23:33:20.624724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8ad1d68f2f'
down_revision = '8e61001e64cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('eye_color', table_name='Characters')
    op.drop_index('eye_color_2', table_name='Characters')
    op.drop_index('gender', table_name='Characters')
    op.drop_index('gender_2', table_name='Characters')
    op.drop_index('hair_color', table_name='Characters')
    op.drop_index('hair_color_2', table_name='Characters')
    op.drop_index('height', table_name='Characters')
    op.drop_index('height_2', table_name='Characters')
    op.drop_index('mass', table_name='Characters')
    op.drop_index('mass_2', table_name='Characters')
    op.drop_index('skin_color', table_name='Characters')
    op.drop_index('skin_color_2', table_name='Characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('skin_color_2', 'Characters', ['skin_color'], unique=False)
    op.create_index('skin_color', 'Characters', ['skin_color'], unique=False)
    op.create_index('mass_2', 'Characters', ['mass'], unique=False)
    op.create_index('mass', 'Characters', ['mass'], unique=False)
    op.create_index('height_2', 'Characters', ['height'], unique=False)
    op.create_index('height', 'Characters', ['height'], unique=False)
    op.create_index('hair_color_2', 'Characters', ['hair_color'], unique=False)
    op.create_index('hair_color', 'Characters', ['hair_color'], unique=False)
    op.create_index('gender_2', 'Characters', ['gender'], unique=False)
    op.create_index('gender', 'Characters', ['gender'], unique=False)
    op.create_index('eye_color_2', 'Characters', ['eye_color'], unique=False)
    op.create_index('eye_color', 'Characters', ['eye_color'], unique=False)
    # ### end Alembic commands ###
